#!/usr/bin/env bun

import { $ } from "bun"
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"
import solidPlugin from "@opentui/solid/bun-plugin"
import type { BunPlugin } from "bun"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import { Script } from "@opencode-ai/script"
import pkg from "../package.json"
import { generateDistNotice } from "./generate-notice"

const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.ts"),
  `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
)
console.log("Generated models-snapshot.ts")

// Load migrations from migration directories
const migrationDirs = (
  await fs.promises.readdir(path.join(dir, "migration"), {
    withFileTypes: true,
  })
)
  .filter((entry) => entry.isDirectory() && /^\d{4}\d{2}\d{2}\d{2}\d{2}\d{2}/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(dir, "migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(
          Number(match[1]),
          Number(match[2]) - 1,
          Number(match[3]),
          Number(match[4]),
          Number(match[5]),
          Number(match[6]),
        )
      : 0
    return { sql, timestamp, name }
  }),
)
console.log(`Loaded ${migrations.length} migrations`)

const singleFlag = process.argv.includes("--single")
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")

const allTargets: {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}[] = [
  {
    os: "linux",
    arch: "arm64",
  },
  {
    os: "linux",
    arch: "x64",
  },
  {
    os: "linux",
    arch: "x64",
    avx2: false,
  },
  {
    os: "linux",
    arch: "arm64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
    avx2: false,
  },
  {
    os: "darwin",
    arch: "arm64",
  },
  {
    os: "darwin",
    arch: "x64",
  },
  {
    os: "darwin",
    arch: "x64",
    avx2: false,
  },
  {
    os: "win32",
    arch: "arm64",
  },
  {
    os: "win32",
    arch: "x64",
  },
  {
    os: "win32",
    arch: "x64",
    avx2: false,
  },
]

const targets = singleFlag
  ? allTargets.filter((item) => {
      if (item.os !== process.platform || item.arch !== process.arch) {
        return false
      }

      // When building for the current platform, prefer a single native binary by default.
      // Baseline binaries require additional Bun artifacts and can be flaky to download.
      if (item.avx2 === false) {
        return baselineFlag
      }

      // also skip abi-specific builds for the same reason
      if (item.abi !== undefined) {
        return false
      }

      return true
    })
  : allTargets

await $`rm -rf dist`

// Generate full distribution NOTICE (static header + all dep license texts)
const repoRoot = path.resolve(dir, "../..")
const { notice: distNotice, deps: depList } = await generateDistNotice(
  path.join(repoRoot, "NOTICE"),
  dir,
)
console.log(`Generated distribution NOTICE (${depList.length} deps)`)

// Write dependency manifest for compliance tracking
await $`mkdir -p dist`
await Bun.write(
  path.join(dir, "dist/dependency-licenses.json"),
  JSON.stringify(depList, null, 2),
)
console.log("Written dist/dependency-licenses.json")

// Read all SKILL.md files to embed as a define constant
const skillsDir = path.resolve(dir, "src/elastic/skills")
const embeddedSkills: Record<string, string> = {}
if (fs.existsSync(skillsDir)) {
  for (const entry of fs.readdirSync(skillsDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue
    const md = path.join(skillsDir, entry.name, "SKILL.md")
    if (fs.existsSync(md)) embeddedSkills[entry.name] = fs.readFileSync(md, "utf8")
  }
  console.log(`Embedded ${Object.keys(embeddedSkills).length} skills`)
}

const binaries: Record<string, string> = {}
if (!skipInstall) {
  await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}
// Derive a base name from the package name, stripping the scope.
// e.g. "@elastic/ramen" → "ramen". The scope is re-added later when
// forming the full npm name, so keeping the scope here would double it up
// (yielding @elastic/elastic-ramen-<platform>).
const pkgBaseName = pkg.name.startsWith("@")
  ? pkg.name.split("/")[1]
  : pkg.name

// Generate static-import shims for cli's es/apis.ts and kb/apis.ts.
// Those files use template-string dynamic imports (`import('./apis/${name}.ts')`)
// which Bun cannot statically analyze. Files outside the bundle root end up at
// $bunfs paths with "../" that don't resolve at runtime. We replace them with
// shims that use concrete @elastic/cli/* path-alias imports so the bundler can
// include each file and assign proper bundle IDs.
async function generateApiShim(kind: "es" | "kb") {
  const sepLiteral = kind === "es" ? "/_([a-z0-9])/g" : "/-([a-z0-9])/g"
  const apiDir = path.resolve(dir, `../cli/src/${kind}/apis`)
  const stems = fs
    .readdirSync(apiDir)
    .filter((f) => f.endsWith(".ts"))
    .map((f) => f.replace(/\.ts$/, ""))
  const entries = stems
    .map((stem) => `  "${stem}": () => import("@elastic/cli/${kind}/apis/${stem}"),`)
    .join("\n")
  const defType = kind === "es" ? "EsApiDefinition" : "KbApiDefinition"
  const manifestExport = kind === "es" ? "apiManifest" : "kbApiManifest"
  const loadFn = kind === "es" ? "loadEsApisInFile" : "loadKbApisInFile"
  const loadOneFn = kind === "es" ? "loadEsApi" : "loadKbApi"
  const loadAllFn = kind === "es" ? "loadAllEsApis" : "loadAllKbApis"
  const metaType = kind === "es" ? "EsApiMeta" : "KbApiMeta"
  const nsEq = kind === "es" ? "(d.namespace ?? null) === meta.namespace" : "d.namespace === meta.namespace"
  const content = `// Auto-generated by build.ts — do not edit
// Replaces @elastic/cli/${kind}/apis.ts template-string dynamic imports with
// static per-file imports that the Bun bundler can analyze and include.
import type { ${defType} } from "@elastic/cli/${kind}/types"
import { ${manifestExport} } from "@elastic/cli/${kind}/api-manifest"
import type { ${metaType} } from "@elastic/cli/${kind}/api-manifest"
export { ${manifestExport} } from "@elastic/cli/${kind}/api-manifest"
export type { ${metaType} } from "@elastic/cli/${kind}/api-manifest"

const moduleCache = new Map<string, Promise<${defType}[]>>()

function toCamelCase(stem: string): string {
  return stem.replace(${sepLiteral}, (_, c: string) => c.toUpperCase())
}

const imports: Record<string, () => Promise<Record<string, ${defType}[]>>> = {
${entries}
}

export async function ${loadFn}(namespaceFile: string): Promise<${defType}[]> {
  const cached = moduleCache.get(namespaceFile)
  if (cached != null) return cached
  const p = (async () => {
    const loader = imports[namespaceFile]
    if (!loader) throw new Error(\`internal error: unknown namespace file: \${namespaceFile}\`)
    const mod = await loader()
    const exportName = toCamelCase(namespaceFile) + "Apis"
    const arr = mod[exportName]
    if (!Array.isArray(arr)) throw new Error(\`internal error: \${namespaceFile} did not export \${exportName}\`)
    return arr as ${defType}[]
  })()
  moduleCache.set(namespaceFile, p)
  return p
}

export async function ${loadOneFn}(meta: ${metaType}): Promise<${defType}> {
  const defs = await ${loadFn}(meta.namespaceFile)
  const found = defs.find((d) => d.name === meta.name && ${nsEq})
  if (!found) {
    const label = meta.namespace ? \`\${meta.namespace} \${meta.name}\` : meta.name
    throw new Error(\`internal error: manifest entry "\${label}" not found in \${meta.namespaceFile}\`)
  }
  return found
}

export async function ${loadAllFn}(): Promise<${defType}[]> {
  const files = new Set(${manifestExport}.map((m) => m.namespaceFile))
  return (await Promise.all([...files].map(${loadFn}))).flat()
}
`
  const out = path.resolve(dir, `src/elastic/cli-${kind}-apis.generated.ts`)
  await Bun.write(out, content)
  return out
}

const [esShim, kbShim] = await Promise.all([generateApiShim("es"), generateApiShim("kb")])
const esApisTarget = path.resolve(dir, "../cli/src/es/apis.ts")
const kbApisTarget = path.resolve(dir, "../cli/src/kb/apis.ts")

// Redirect imports of cli's apis.ts files to the generated static-import shims.
const cliApisPlugin: BunPlugin = {
  name: "elastic-cli-apis-shim",
  setup(build) {
    build.onResolve({ filter: /apis(\.ts)?$/ }, (args) => {
      if (!args.importer) return
      const resolved = path.resolve(path.dirname(args.importer), args.path.replace(/\.ts$/, "") + ".ts")
      if (resolved === esApisTarget) return { path: esShim }
      if (resolved === kbApisTarget) return { path: kbShim }
    })
  },
}

// Redirect @elastic/es-schemas/*.js imports to their TypeScript source.
// The package ships no dist/ directory inside the monorepo, so the "import"
// export condition ("./dist/*.js") would fail; map directly to src/*.ts instead.
const esSchemasPlugin: BunPlugin = {
  name: "elastic-es-schemas",
  setup(build) {
    const schemasRoot = path.resolve(dir, "../cli/packages/es-schemas/src")
    build.onResolve({ filter: /^@elastic\/es-schemas/ }, (args) => {
      const sub = args.path.replace("@elastic/es-schemas/", "").replace(/\.js$/, ".ts")
      return { path: sub === "@elastic/es-schemas" ? path.join(schemasRoot, "index.ts") : path.join(schemasRoot, sub) }
    })
  },
}

for (const item of targets) {
  const name = [
    pkgBaseName,
    // changing to win32 flags npm for some reason
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi === undefined ? undefined : item.abi,
  ]
    .filter(Boolean)
    .join("-")
  console.log(`building ${name}`)
  await $`mkdir -p dist/${name}/bin`

  const localPath = path.resolve(dir, "node_modules/@opentui/core/parser.worker.js")
  const rootPath = path.resolve(dir, "../../node_modules/@opentui/core/parser.worker.js")
  const parserWorker = fs.realpathSync(fs.existsSync(localPath) ? localPath : rootPath)
  const workerPath = "./src/cli/cmd/tui/worker.ts"

  // Use platform-specific bunfs root path based on target OS
  const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
  const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [solidPlugin, cliApisPlugin, esSchemasPlugin],
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: name.replace(pkgBaseName, "bun") as any,
      outfile: `dist/${name}/bin/elastic-ramen`,
      execArgv: [`--user-agent=opencode/${Script.version}`, "--use-system-ca", "--"],
      windows: {},
    },
    entrypoints: ["./src/index.ts", parserWorker, workerPath],
    define: {
      OPENCODE_VERSION: `'${Script.version}'`,
      OPENCODE_MIGRATIONS: JSON.stringify(migrations),
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      OPENCODE_WORKER_PATH: workerPath,
      OPENCODE_CHANNEL: `'${Script.channel}'`,
      OPENCODE_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
      ELASTIC_SKILLS_EMBEDDED: JSON.stringify(embeddedSkills),
    },
  })

  await $`rm -rf ./dist/${name}/bin/tui`

  // npm package name: scoped if the main package is scoped (e.g. @elastic/ramen-darwin-arm64)
  const scope = pkg.name.startsWith("@") ? pkg.name.split("/")[0] + "/" : ""
  const npmName = scope + name

  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name: npmName,
        version: Script.version,
        os: [item.os],
        cpu: [item.arch],
        repository: pkg.repository,
        license: pkg.license,
      },
      null,
      2,
    ),
  )
  binaries[npmName] = Script.version
}

if (Script.release) {
  // Write legal files into each platform bin dir so they are included in the archive.
  // NOTICE is the fully-generated version (static header + all dep license texts).
  const licensePath = path.join(repoRoot, "LICENSE")

  for (const key of Object.keys(binaries)) {
    const dirName = key.replace(/^@[^/]+\//, "")
    const binDir = path.join(dir, `dist/${dirName}/bin`)
    await Bun.write(path.join(binDir, "NOTICE"), distNotice)
    if (fs.existsSync(licensePath)) {
      fs.copyFileSync(licensePath, path.join(binDir, "LICENSE"))
    }
    const bin =
      ["elastic-ramen", "elastic-ramen.exe"].find((file) => fs.existsSync(path.join(binDir, file))) ??
      (key.includes("windows") ? "elastic-ramen.exe" : "elastic-ramen")
    const files = [bin, "NOTICE"]
    if (fs.existsSync(path.join(binDir, "LICENSE"))) {
      files.push("LICENSE")
    }
    if (key.includes("linux")) {
      await $`tar -czf ../../${dirName}.tar.gz ${files}`.cwd(binDir)
    } else {
      await $`zip -r ../../${dirName}.zip ${files}`.cwd(binDir)
    }
  }
  await $`gh release upload v${Script.version} ./dist/*.zip ./dist/*.tar.gz --clobber --repo ${process.env.GH_REPO}`
}

export { binaries }
